version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "3001:5432"
  web:
    build: ./web
    command: bash -c "rails db:migrate"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./web:/skittles-br:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
  webpacker:
    image: skittles-br_web
    command: ["./webpack_dev.sh"]
    volumes:
      - ./web:/skittles-br:cached
    ports:
      - 3035:3035
    depends_on:
      - db
      - web
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./tmp/redis:/data
  flag-generator:
    build: ./flag-generator
    command: ./flag-generator
    ports:
      - "3002:3002"
