class NameGenerator {
  static newName () {
    const names = [
      "Republic of Amora",
      "Dawn Syndicate",
      "South Dreamland",
      "Central Sepore Tswather",
      "Ofhajavire",
      "Iand Naunialand",
      "Chadcavo Territories",
      "South Mani Inai",
      "Northern Kyrgia Rynited",
      "Morkey",
      "Zamlu",
      "Lizevo Giamal",
      "Ticsle Slandsbacia Lands",
      "Bapan Josau",
      "Ofquenatomene",
      "Southern Maarnabar",
      "Alau Puras",
      "Daba",
      "Gasout Haelu",
      "Lecantifi",
      "Ofsouthrab",
      "Isle of Rulaand",
      "Galnitedto",
      "Guaystanthai Lands",
      "Biale Nicookdia",
      "Meandko",
      "Isle of Thuaegaverde",
      "Cayiru",
      "Androc",
      "Uca",
      "Sintsia Biadines",
      "Sopo",
      "Paandlau",
      "Northboslands Lands",
      "Saintkhstan Porbri",
      "Nambocro",
      "Gya",
      "Andrun",
      "Coneithioratedmau",
      "Rdanbou Denshall",
      "Emasli",
      "Dianncipe Niatar",
      "Scotmas Naniso Island",
      "Puu",
      "Ninmo",
      "Waitcaosouth Territories",
      "Buva",
      "Noni Jinua",
      "Innor",
      "Cuna Rigam",
      "Guiti Pomyntarc",
      "Friland Tzerriablic",
      "Spainja Theandnia",
      "Seymoa",
      "Costa Frenchbe Tucen",
      "Tiar Nore",
      "Kide Walesslandlip",
      "Feki Sniazstan",
      "Mengreece",
      "Ugo Aingman",
      "Paandprusque",
      "Blicbo",
      "Siaosou",
      "Landlaukiazueria",
      "Falastan",
      "Niace",
      "Southlinemo",
      "Guara",
      "Naland Liapure",
      "Nechten",
      "Guasocar",
      "Elcoginniador",
      "Loupefincape",
      "Central Markganzimsia",
      "Ofldives Quaca Lands",
      "Isle of Taina Limisee",
      "Haipa Alle",
      "Gualiamerigeor Territories",
      "Makeelingtibeba",
      "Landlafa",
      "Kuri Taof",
      "Marngo Ritama",
      "Dupinessatia",
      "Slandssval Slandsva Republic",
      "Vaze Keho",
      "Slandskitts Lisiacan",
      "Ranbuto",
      "Pabubia",
      "Puamu",
      "Manmyan Thesau",
      "Gallomi",
      "Saosu Contser",
      "Restates Biara",
      "Niagercoastna",
      "Slandslonbel",
      "Russey Geco",
      "Saintlia",
      "Rain Manea",
      "Straniraleoneny",
      "Liscobral",
      "Agui Ngoaulkland",
      "Maname Puerbar",
      "Republic of Janpu Wanblic"
    ]
    return names[Math.floor(Math.random() * names.length)]
  }
}
export default NameGenerator;