# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9bf0f34e99f3a5c959040294d7fd3fad642f71265cbd6731f0ecb778a3eb33a7e94ec56b708a91496ff0377c39c167868ed3d6baade869468f2b3d033542d33a

test:
  secret_key_base: 95a512b6d95c9ce25f90dcc44df6715efad211ce7c4e23bd8466a003bfd3f0d792054cde7fee40721da15d04291d0bed591bfcf1b909aec5cd3e0e237da52d70

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
